export enum SKAdNetworkConversionValue {
    INSTALLATION = 0,
    INSCRIPTION = 1,
    ONE_RECIPE_GENERATED = 4,
    THREE_RECIPES_GENERATED = 6,
    QUOTA_REACHED = 10,
    CHECKOUT_INITIATED = 22,
    CREDIT_PURCHASE = 40,
    PREMIUM_SUBSCRIPTION = 63,
}
